export const MATCH_APP_DELEGATE_IMPORTS_OBJCPP = /#import "AppDelegate\.h"/;
export const MATCH_APP_DELEGATE_IMPORTS_SWIFT = /@UIApplicationMain/;
export const MATCH_FINISH_LAUNCHING_METHOD_OBJCPP =
  /-\s*\(BOOL\)\s*application:\s*\(UIApplication\s*\*\s*\)\s*\w+\s+didFinishLaunchingWithOptions:/g;
export const MATCH_FINISH_LAUNCHING_METHOD_SWIFT =
  /\bsuper\.application\(\w+?, didFinishLaunchingWithOptions: \w+?\)/g;

export const getBridgeHeaderObjC = (projectName: string) => `//
//  VibesBridge.h
//  ${projectName}
//
//  Generated by expo-vibes-sdk plugin
//

#import <Foundation/Foundation.h>

@interface VibesBridge : NSObject

+ (void)configureVibes;

@end
`;

export const getBridgeImplementationObjC = (
  projectName: string,
  appId: string,
  appUrl?: string,
): string => {
  const apiUrlValue = appUrl ? `@"${appUrl}"` : "NULL";
  const trackingApiUrlValue = appUrl ? `@"${appUrl}"` : "NULL";

  return `//
//  VibesBridge.m
//  ${projectName}
//
//  Generated by expo-vibes-sdk plugin
//

#import <Foundation/Foundation.h>
#import "VibesBridge.h"
@import VibesPush;

@implementation VibesBridge

+ (void)configureVibes
{
  VibesConfiguration *vibesConfig = [[VibesConfiguration alloc] initWithAdvertisingId:NULL
                                                                                  apiUrl:${apiUrlValue}
                                                                         trackingApiUrl:${trackingApiUrlValue}
                                                                                  logger:NULL
                                                                             storageType:VibesStorageEnumUSERDEFAULTS
                                                                       trackedEventTypes:[@[] mutableCopy]];
  [Vibes configureWithAppId:@"${appId}"
              configuration:vibesConfig];
}

@end
`;
};

// Objcpp App Delegate Vibes Bridge

export const IMPORT_VIBES_BRIDGE_OBJCPP = `#import "VibesBridge.h"`;
export const CONFIGURE_VIBES_BRIDGE_OBJCPP = `  [VibesBridge configureVibes];`;

// Swift App Delegate Vibes Config
export const IMPORT_VIBES_PACKAGE_SWIFT = `import VibesPush`;

export const getOptionalConfigLinesSwift = (appId: string, appUrl: string) => [
  `    let configuration = VibesConfiguration(`,
  `      advertisingId: nil,`,
  `      apiUrl: "${appUrl}",`,
  `      logger: nil,`,
  `      storageType: .USERDEFAULTS,`,
  `      trackedEventTypes: [TrackedEventType.launch, TrackedEventType.clickthru] as NSArray`,
  `    )`,
  `    Vibes.configure(appId: "${appId}", configuration: configuration)`,
];

export const getConfigLineSwift = (appId: string) =>
  `    Vibes.configure(appId: "${appId}")`; 