// Anchors RegExp
export const MATCH_APP_DELEGATE_IMPORTS_OBJCPP = /#import "AppDelegate\.h"/;
export const MATCH_APP_DELEGATE_IMPORTS_SWIFT = /@UIApplicationMain/;
export const MATCH_FINISH_LAUNCHING_METHOD_OBJCPP =
  /-\s*\(BOOL\)\s*application:\s*\(UIApplication\s*\*\s*\)\s*\w+\s+didFinishLaunchingWithOptions:/g;
export const MATCH_FINISH_LAUNCHING_METHOD_SWIFT =
  /\bsuper\.application\(\w+?, didFinishLaunchingWithOptions: \w+?\)/g;
export const MATCH_DID_REGISTER_REMOTE_NOTIFICATIONS_OBJCPP =
  /-\s*\(void\)\s*application:\s*\(UIApplication\s*\*\s*\)\s*\w+\s+didRegisterForRemoteNotificationsWithDeviceToken:/g;

// Objective C Bridge for Vibes configuration
export const getBridgeHeaderObjC = (projectName: string) => `//
//  VibesBridge.h
//  ${projectName}
//
//  Generated by expo-vibes-sdk plugin
//

#import <Foundation/Foundation.h>

@interface VibesBridge : NSObject

+ (void)configureVibes;
+ (void)requestAuthorizationForNotifications;
+ (void)setPushToken:(NSData *)data;

@end
`;

export const getBridgeImplementationObjC = (
  projectName: string,
  appId: string,
  appUrl?: string,
): string => {
  const apiUrlValue = appUrl ? `@"${appUrl}"` : "NULL";
  const trackingApiUrlValue = appUrl ? `@"${appUrl}"` : "NULL";

  return `//
//  VibesBridge.m
//  ${projectName}
//
//  Generated by expo-vibes-sdk plugin
//

#import <Foundation/Foundation.h>
#import "VibesBridge.h"
@import VibesPush;
#import <UserNotifications/UNUserNotificationCenter.h>

@implementation VibesBridge

+ (void)configureVibes
{
  VibesConfiguration *vibesConfig = [[VibesConfiguration alloc] initWithAdvertisingId:NULL
                                                                                  apiUrl:${apiUrlValue}
                                                                         trackingApiUrl:${trackingApiUrlValue}
                                                                                  logger:NULL
                                                                             storageType:VibesStorageEnumUSERDEFAULTS
                                                                       trackedEventTypes:[@[] mutableCopy]];
  [Vibes configureWithAppId:@"${appId}"
              configuration:vibesConfig];
}

+ (void)requestAuthorizationForNotifications {
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0
    [[UIApplication sharedApplication] registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];
    [[UIApplication sharedApplication] registerForRemoteNotifications];
#else
    UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
    center.delegate = self;
    [center requestAuthorizationWithOptions:(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge)
                          completionHandler:^(BOOL granted, NSError *_Nullable error) {
      NSLog(@"[VIBES] <requesting permissions>");
      if (error) {
            NSLog(@"ERROR registering for push: %@ - %@", error.localizedFailureReason, error.localizedDescription);
        } else if (granted) {
          NSLog(@"[VIBES] <permission granted>");
            dispatch_async(dispatch_get_main_queue(), ^{
                               [[UIApplication sharedApplication] registerForRemoteNotifications];
                           });
        } else {
            NSLog(@"authorization denied for push");
        }
    }];
#endif
}

+ (void)setPushToken:(NSData *)data {
  NSLog(@"[VIBES] <set push token, > %@", data);
  [[Vibes shared] setPushTokenFromData:data];
  NSLog(@"[VIBES] <completed> %@");
}

@end
`;
};

// Objcpp App Delegate Vibes Bridge

export const IMPORT_VIBES_BRIDGE_OBJCPP = `#import "../VibesBridge.h"`;
export const CONFIGURE_VIBES_BRIDGE_OBJCPP = `  [VibesBridge configureVibes];`;
export const DID_REGISTER_REMOTE_NOTIFICATIONS_OBJCPP = `- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  NSLog(@"[VIBES] <did register for remote notfs>");
  
  [VibesBridge setPushToken:deviceToken];
  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}`;

// Swift App Delegate Vibes Config
export const IMPORT_VIBES_PACKAGE_SWIFT = `import VibesPush`;

export const getOptionalConfigLinesSwift = (appId: string, appUrl: string) => [
  `    let configuration = VibesConfiguration(`,
  `      advertisingId: nil,`,
  `      apiUrl: "${appUrl}",`,
  `      logger: nil,`,
  `      storageType: .USERDEFAULTS,`,
  `      trackedEventTypes: [TrackedEventType.launch, TrackedEventType.clickthru] as NSArray`,
  `    )`,
  `    Vibes.configure(appId: "${appId}", configuration: configuration)`,
];

export const getConfigLineSwift = (appId: string) =>
  `    Vibes.configure(appId: "${appId}")`;
